default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: db/primary.sqlite3
    migrations_paths: db/migrate
  primary_replica:
    <<: *default
    database: db/primary_replica.sqlite3
    replica: true
  secondary:
    <<: *default
    database: db/secondary.sqlite3
    migrations_paths: db/secondary_migrate
  secondary_replica:
    <<: *default
    database: db/secondary_replica.sqlite3
    replica: true

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
