default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: db/development.sqlite3
    migrations_paths: db/migrate
  secondary:
    <<: *default
    database: db/development_secondary.sqlite3
    migrations_paths: db/secondary_migrate

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
